language: csharp
mono:
    - latest
script:
    - cd src/DiscordCLI
	- cd restore DiscordCLI.sln
	- xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release DBSharp.sln
notifications:
  email:
    recipients:
      - me@d3v.no
    on_success: change
    on_failure: always